# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create! product_title: "Lorem ipsum dolor sit amet", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/6_CATERS_cats_and_bunnies_02-1024x829.jpg"
Product.create! product_title: "Maecenas efficitur magna massa", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/06-train-cat-shake-hands-1024x682.jpg"
Product.create! product_title: "Nullam non rutrum lectus", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/08-cat-cancer-4.jpeg"
Product.create! product_title: "Praesent commodo eleifend velit gravida pretium", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/03008-Cute-Birman-kitten-and-rabbit-white-background.jpg"
Product.create! product_title: "Nunc facilisis sem ut laoreet mollis", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/32445_petsproducts_march-pets-site-flip-vertical-store_8_vd-hero_1920x693._CB299747913_.jpg"
Product.create! product_title: "Mauris gravida gravida leo", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/75552.adapt.1900.1.jpg"
Product.create! product_title: "Vivamus cursus enim eu nisi cursus", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/6784063-cute-cats-hd.jpg"
Product.create! product_title: "Phasellus auctor interdum velit eget", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/867478090.jpg.1513100310.jpg"
Product.create! product_title: "Duis rutrum, velit ac volutpat", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/cat.jpg"
Product.create! product_title: "Ut maximus metus at luctus tincidunt", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/cat (1).jpg"
Product.create! product_title: "Pellentesque auctor iaculis ex", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/Cat for lost page.jpg"
Product.create! product_title: "Phasellus volutpat eros ac metus", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/cat-pet-animal-domestic-104827.jpeg"
Product.create! product_title: "Suspendisse potenti", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/Cauliflower.JPG"
Product.create! product_title: "Cras porta tellus vel mi ultrices", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/Cute_cat_1.jpg"
Product.create! product_title: "Quisque accumsan vulputate ipsum", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/ginger-kitten-cuddle-with-adult-tabby-cat--459759125-599342aa054ad90011f480a9.jpg"
Product.create! product_title: "Vestibulum nec enim velit", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/LittleCats_9.jpg"
Product.create! product_title: "Nullam ultrices ullamcorper orci id gravida", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/maxresdefault.jpg"
Product.create! product_title: "Morbi elementum purus metus", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/maxresdefault (1).jpg"
Product.create! product_title: "Vestibulum ullamcorper risus sed", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/maxresdefault (2).jpg"
Product.create! product_title: "Curabitur semper magna lorem", product_description: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam.", product_price: "19", product_img_url: "assets/images/smush-the-cat-1.jpg"
